keen/query-creator

- public/locales/en/translation.json
- src/components/Extraction/Extraction.test.tsx
- src/components/Extraction/Extraction.tsx
- src/components/Extraction/constants.ts
https://metakeen.atlassian.net/browse/FEE-284
> fix: 🐛 extraction tooltip

- src/components/Filters/Filters.styles.ts
- src/components/Filters/Filters.tsx
https://metakeen.atlassian.net/browse/FEE-290
> fix: 🐛 filter values overlap

- src/components/Filters/components/FilterListValue/FilterListValue.tsx
- Small refactor for better performance and avoid creating function for each re-render.
> refactor: 💡 update handler for filterslist values

- src/modules/chartSettings/reducer.test.ts
- src/modules/events/reducer.test.ts
- src/saga.ts
- Setup default timezone for queries that do not have defined timezone.
- Added missing reducers unit tests.
> fix: 🐛 set default timezone

- src/components/Extraction/components/ExtractionProperties/ExtractionProperties.styles.ts
- src/components/Extraction/components/ExtractionProperties/ExtractionProperties.tsx
- src/components/Extraction/components/ExtractionProperties/constants.ts
- src/components/GroupBy/GroupBy.styles.tsx
- src/components/GroupBy/GroupBy.tsx
- src/components/GroupBy/constants.ts
- src/components/OrderBy/OrderBy.styles.tsx
- src/components/OrderBy/OrderBy.test.tsx
- src/components/OrderBy/OrderBy.tsx
- src/components/OrderBy/components/OrderByProperty/OrderByProperty.styles.ts
- src/components/OrderBy/components/OrderByProperty/OrderByProperty.tsx
- src/components/OrderBy/constants.ts
- src/components/SearchableProperty/SearchableProperty.styles.ts
- src/components/SearchableProperty/SearchableProperty.tsx
- yarn.lock
> feat: 🎸 Added drag handle to draggable properties

- package.json
- tsconfig.json
Closes: 
[#FEE-356](https://metakeen.atlassian.net/jira/software/projects/FEE/boards/10?selectedIssue=FEE-356)
> fix: 🐛 Configured package build to include declaration files

- src/App.styles.ts
- src/components/Filters/components/Filter/Filter.styles.ts
- src/components/Filters/components/FilterListValue/FilterListValue.styles.ts
- src/components/Filters/components/FilterListValue/FilterListValue.tsx
- src/components/Filters/components/FilterListValue/constants.ts
- src/components/FunnelStep/FunnelStep.styles.ts
https://metakeen.atlassian.net/browse/FEE-363
> fix: 🐛 add scroll to <FilterListValue>

- src/index.ts
https://metakeen.atlassian.net/browse/FEE-327
> chore: 🤖 export transformToQuery

- .babelrc
- .eslintignore
- .gitignore
- README.md
- package.json
- src/App.styles.ts
- src/components/Analysis/components/ListItem.styles.ts
- src/components/DatePicker/DatePicker.styles.ts
- src/components/DropableContainer/DropableContainer.styles.ts
- src/components/DropdownList/DropdownList.styles.ts
- src/components/Filters/components/PropertyTypeCast/PropertyTypeCast.styles.ts
- src/components/Hint/Hint.styles.ts
- src/components/Input/Input.styles.ts
- src/components/PropertiesTree/components/TreeLeaf/TreeLeaf.styles.ts
- src/components/PropertyGroup/PropertyGroup.styles.ts
- src/components/SupportedInterval/SupportedInterval.styles.ts
- src/components/Title/Title.styles.ts
- tsconfig.json
- yarn.lock
Closes: [FEE-456](https://metakeen.atlassian.net/jira/software/projects/FEE/boards/10?selectedIssue=FEE-456)
> chore: 🤖 Changed application build to increase CSS specificity

- public/locales/en/translation.json
- src/components/Timeframe/Timeframe.styles.ts
- src/components/Timeframe/Timeframe.test.tsx
- src/components/Timeframe/Timeframe.tsx
https://metakeen.atlassian.net/browse/FEE-485
> feat: 🎸 add timezone notification

- .gitignore
https://metakeen.atlassian.net/browse/FEE-523
> refactor: 💡 remove package-lock.json from git

- src/components/OrderBy/components/DirectionList/DirectionList.styles.ts
- src/components/OrderBy/components/DirectionList/DirectionList.tsx
- src/components/OrderBy/components/OrderByProperty/OrderByProperty.styles.ts
- yarn.lock
Closes: [https://metakeen.atlassian.net/browse/FEE-536](https://metakeen.atlassian.net/browse/FEE-536)
> fix: 🐛 Dropable container - transparent variant used

- src/components/PropertyPath/PropertyPath.styles.ts
- src/components/PropertyPath/PropertyPath.test.tsx
- src/components/PropertyPath/PropertyPath.tsx
https://metakeen.atlassian.net/browse/FEE-558
> fix: 🐛 long target property

- public/locales/en/translation.json
- src/components/EventCollection/EventCollection.tsx
- src/components/FunnelStep/FunnelStep.styles.ts
- src/components/PropertyPath/PropertyPath.styles.ts
- src/components/PropertyPath/PropertyPath.test.tsx
- src/components/PropertyPath/PropertyPath.tsx
- src/components/QueryArguments/QueryArguments.styles.ts
- src/components/Timeframe/components/AbsoluteTimeLabel/AbsoluteTimeLabel.styles.ts
- src/components/Timeframe/components/AbsoluteTimeLabel/AbsoluteTimeLabel.test.tsx
- src/components/Timeframe/components/AbsoluteTimeLabel/AbsoluteTimeLabel.tsx
- src/components/Timeframe/components/RelativeTimeLabel/RelativeTimeLabel.styles.ts
- src/components/Timeframe/components/RelativeTimeLabel/RelativeTimeLabel.tsx
* https://metakeen.atlassian.net/browse/FEE-560
* https://metakeen.atlassian.net/browse/FEE-272
* https://metakeen.atlassian.net/browse/FEE-352
> feat: 🎸 support rwd in layout

- src/components/GroupBy/GroupBy.tsx
> fix: 🐛 restore GroupBy margin

- src/App.styles.ts
- src/App.tsx
- src/components/Analysis/Analysis.tsx
- src/components/EventCollection/EventCollection.tsx
- src/components/Extraction/Extraction.styles.ts
- src/components/Extraction/Extraction.tsx
- src/components/Extraction/components/ExtractionTitle/ExtractionTitle.styles.ts
- src/components/Filters/Filters.styles.ts
- src/components/Filters/Filters.tsx
- src/components/QueryArguments/QueryArguments.styles.ts
- src/components/TargetProperty/TargetProperty.tsx
- src/components/Timeframe/Timeframe.tsx
https://metakeen.atlassian.net/browse/FEE-582
> style: 💄 add responsive layout for groupBy/orderBy

- public/locales/en/translation.json
- src/components/Filters/components/FilterValue/FilterValue.tsx
- src/components/Filters/components/FilterValue/types.ts
https://metakeen.atlassian.net/browse/FEE-550
> feat: 🎸 add placeholder for filters text input

- src/components/TargetProperty/constants.ts
[FEE-507](https://metakeen.atlassian.net/jira/software/projects/FEE/boards/10?selectedIssue=FEE-507)
> feat: 🎸 Percentile analysis - numeric data required tooltip

- src/components/TargetProperty/constants.ts
https://metakeen.atlassian.net/browse/FEE-507
> feat: 🎸 Percentile analysis - numeric data required tooltip (#87)

- .circleci/config.yml
https://metakeen.atlassian.net/browse/FEE-793
> chore: 🤖 update docker image for node

- src/components/Limit/Limit.tsx
https://metakeen.atlassian.net/jira/software/projects/FEE/boards/10/backlog?selectedIssue=FEE-845
> fix: 🐛 Clear limit field on group by change

- src/components/OrderBy/OrderBy.tsx
- src/components/OrderBy/constants.ts
https://metakeen.atlassian.net/browse/FEE-868
> fix: 🐛 query with multiple orderBy

- src/components/Filters/components/FilterValue/FilterValue.tsx
https://metakeen.atlassian.net/browse/FEE-865
> fix: 🐛 map filters suggestions to string
